version: '3.7'

services:
  server:
    build:
      context: ./server
    image: myapp-server
    container_name: myapp-node-server
    command: npm start
    volumes:
      - ./server/:/usr/src/app
    ports:
      - "4000:4000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    
  # mongo:
  #   image: mongo
  #   volumes:
  #     - data-volume:/data/db
  #   ports:
  #     - "27017:27017"
  
  client:
    build:
      context: ./client
    image: myapp-client
    container_name: myapp-react-client
    command: npm run dev
    volumes:
      - ./client/:/usr/src/app
    depends_on:
      - server
    ports:
      - "5173:5173"

volumes:
    data-volume:
    web-root:
      driver: local